-- [nfnl] Compiled from fnl/config/keybind.fnl by https://github.com/Olical/nfnl, do not edit.
local function set_normal(k, command, opts)
  return vim.keymap.set("n", k, command, vim.tbl_extend("force", {noremap = true, silent = true, nowait = true}, opts))
end
local function set_terminal(k, command, opts)
  return vim.keymap.set("t", k, command, vim.tbl_extend("force", {noremap = true, silent = true, nowait = true}, opts))
end
local function telescope(command, theme)
  return (":Telescope " .. command .. " theme=" .. theme .. "<cr>")
end
local function set_normal_telescope(k, command, theme)
  return set_normal(k, telescope(command, theme), {desc = ("tele " .. command)})
end
set_normal_telescope("<leader>f*", "grep_string", "dropdown")
set_normal_telescope("<leader>f/", "current_buffer_fuzzy_find", "dropdown")
set_normal_telescope("<leader>fa", "autocommands", "dropdown")
set_normal_telescope("<leader>fb", "buffers", "dropdown")
set_normal_telescope("<leader>fc", "commands", "dropdown")
set_normal_telescope("<leader>fch", "command_history", "dropdown")
set_normal_telescope("<leader>fd", "diagnostics", "dropdown")
set_normal_telescope("<leader>ff", "file_browser", "dropdown")
set_normal_telescope("<leader>fg", "git_files", "dropdown")
set_normal_telescope("<leader>fh", "help_tags", "dropdown")
set_normal_telescope("<leader>fj", "jumplist", "dropdown")
set_normal_telescope("<leader>fk", "keymaps", "dropdown")
set_normal_telescope("<leader>fl", "live_grep", "dropdown")
set_normal_telescope("<leader>fm", "marks", "dropdown")
set_normal_telescope("<leader>fn", "resume", "dropdown")
set_normal_telescope("<leader>fo", "oldfiles", "dropdown")
set_normal_telescope("<leader>fp", "builtin", "dropdown")
set_normal_telescope("<leader>fr", "registers", "dropdown")
set_normal_telescope("<leader>fs", "search_history", "dropdown")
set_normal_telescope("<leader>ft", "filetypes", "dropdown")
set_normal_telescope("<leader>fv", "vim_options", "dropdown")
set_normal_telescope("<leader>lb", "lsp_document_symbols", "dropdown")
set_normal_telescope("<leader>lci", "lsp_incoming_calls", "dropdown")
set_normal_telescope("<leader>lco", "lsp_outgoing_calls", "dropdown")
set_normal_telescope("<leader>ld", "lsp_definitions", "dropdown")
set_normal_telescope("<leader>li", "lsp_implementations", "dropdown")
set_normal_telescope("<leader>lr", "lsp_references", "dropdown")
set_normal_telescope("<leader>ls", "lsp_dynamic_workspace_symbols", "dropdown")
set_normal_telescope("<leader>lt", "lsp_type_definitions", "dropdown")
set_normal_telescope("<leader>lw", "lsp_workspace_symbols", "dropdown")
set_normal_telescope("<leader>gc", "git_commits", "dropdown")
set_normal_telescope("<leader>gb", "git_bcommits", "dropdown")
set_normal_telescope("<leader>gh", "git_branches", "dropdown")
set_normal_telescope("<leader>gs", "git_status", "dropdown")
set_normal("<leader>gn", ":Git switch -c ", {desc = "new branch", silent = false})
set_normal_telescope("<leader>xh", "http list", "dropdown")
set_normal_telescope("<leader>xu", "undo", "dropdown")
set_normal("<leader>lls", ":lua vim.lsp.codelens.run()<CR>", {desc = "codelens: run"})
set_normal("<leader>llr", ":lua vim.lsp.codelens.refresh()<CR>", {desc = "codelens: refresh"})
set_terminal("<Esc>", "<C-\\><C-n>", {desc = "nvim-tree: toggle"})
set_normal("<leader><space>", ":ToggleTerm<CR>", {desc = "toggleterm"})
return {}
